### ISSUE TITLE
Fedoraloader doesnt work

### ISSUE THREAD

**Issue by ProjectileAimbotError404** [Fedoraware/Fedoraloader#13]
I tried opening fedoraloader and it showed me the "Do you want this app from an unknown publisher to make changes to your device", and i press "yes" as usual, but fedoraloader doesnt open, or show any response. Anyone who has the same issue/had the same issue and resolved it?

**Comment by lnx00** [comment]
Check the tray menu for the Fedoraware icon:
![](https://github.com/Fedoraware/Fedoraloader/raw/master/.github/assets/Preview.png)

**Comment by ProjectileAimbotError404** [comment]
> Check the tray menu for the Fedoraware icon. If it doesn't appear, make sure that you antivirus isn't blocking the application. ![](https://github.com/Fedoraware/Fedoraloader/raw/master/.github/assets/Preview.png)

trey menu? what is that?

**Comment by ProjectileAimbotError404** [comment]
nevermind, everything works
