### ISSUE TITLE
More of an enhancement than an issue, change the way vac bypass works on loader.

### ISSUE THREAD

**Issue by Umbrozium** [Fedoraware/Fedoraloader#3]
Very good release btw, nice job! The only thing I'd have changed though is remove VAC Bypass from launch options and instead make it a new "check/uncheck" button besides "load" and "load and exit" when you open it.

**Comment by lnx00** [comment]
Will be added in the next update:
![Preview](https://i.imgur.com/PiJwQaj.png)

**Comment by Umbrozium** [comment]
Absolutely incredible 💯

**Comment by lnx00** [comment]
It's available in the latest release.
