### ISSUE TITLE
I'm having a certain problem with the loader.

### ISSUE THREAD

**Issue by TJayz2** [Fedoraware/Fedoraloader#4]
Well, hello!

i am new to this all type of cheating in TF2 kind of thing, and i discovered fedoraware, i've been trying to download it for the past couple of days but without any success. i have managed to download it just now and got the loader, but everytime i try to load the cheat, it keeps saying: 'Loading... Please wait until the game is ready.', i dont know what's causing this problem because i always keep the game open before trying to load the cheat.

i just wanted to know if there is some fix to this?
![fedoraloader problem](https://github.com/Fedoraware/Fedoraloader/assets/147219407/1485d9a7-5922-45ab-9396-15f52cc8314d)

**Comment by GC634** [comment]
Close the game. And close steam. And then start Fedora loader and inject it.

**Comment by lnx00** [comment]
It seems that you're using Windows 7. It's outdated and neither supported by Steam nor Fedoraloader anymore.

**Comment by GC634** [comment]
Or upgrade to at least windows 10

**Comment by TJayz2** [comment]
> It seems that you're using Windows 7. It's outdated and neither supported by Steam nor Fedoraloader anymore.
> 
> Your only option is to try loading without VAC bypass (and manually starting the game) or use a different injector that supports your windows version.

I see.

Well, right now i have an injector that works with fedoraware, but i cannot compile it into a DLL, is it possible you can possibly put it in here?

**Comment by TJayz2** [comment]
> Close the game. And close steam. And then start Fedora loader and inject it.

I tried

**Comment by lnx00** [comment]
> Well, right now i have an injector that works with fedoraware, but i cannot compile it into a DLL, is it possible you can upload the file here?

There's a [download link](https://nightly.link/Fedoraware/Fedoraware/workflows/msbuild/main/Fedoraware.zip) on the Fedoraware repository:

**Comment by TJayz2** [comment]
> > Well, right now i have an injector that works with fedoraware, but i cannot compile it into a DLL, is it possible you can upload the file here?
> 
> There's a [download link](https://nightly.link/Fedoraware/Fedoraware/workflows/msbuild/main/Fedoraware.zip) on the Fedoraware repository.

Thanks, i appreciate it!
