### ISSUE TITLE
issue with injecting

### ISSUE THREAD

**Issue by 0xziess** [Fedoraware/Fedoraloader#5]
everytime i try to load fedora it shows me a error
---------------------------
Pattern not found
---------------------------
Module: client.dll
Pattern: 55 8B EC 83 EC ? 56 8B 75 ? 57 8B 7D ? 8B C7
Address: 0x0 (+0)
---------------------------
OK   
---------------------------

**Comment by lnx00** [comment]
https://github.com/Fedoraware/Fedoraware/issues/1059
