### ISSUE TITLE
Pattern not found error

### ISSUE THREAD

**Issue by poptartiguess** [Fedoraware/Fedoraloader#9]
I'm using a win 64 bit computer with the dx level set to 90 and whenever I try to launch tf2 with the cheat enabled it fails and gives me said error message
![image](https://github.com/Fedoraware/Fedoraloader/assets/125616049/0f496cf8-8007-42ed-93fd-749c3c98b2fb)

**Comment by lnx00** [comment]
https://github.com/Fedoraware/Fedoraware/issues/1059
